using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

namespace LOLItems.custom_class_data
{
    public enum Items
    {
        MagicLamp = 0, //
        Winchester = 1, //
        Thompson = 2, //
        Screecher = 3, //
        StickyCrossbow = 4, //
        Awp = 5, //
        Zorgun = 6, //
        Barrel = 7, //
        Bow = 8, //
        DuelingPistol = 9, //
        MegaDouser = 10, //
        Crossbow = 12, //
        Thunderclap = 13, //
        BeeHive = 14, //
        Ak47 = 15, //
        YariLauncher = 16, //
        HeckBlaster = 17, //
        Blooper = 18, //
        GrenadeLauncher = 19, //
        Moonscraper = 20, //
        Bsg = 21, //
        ShadesRevolver = 22, //
        DungeonEagle = 23, //
        DartGun = 24, //
        M1 = 25, //
        NailGun = 26, //
        LightGun = 27, //
        Mailbox = 28, //
        Vertebraek47 = 29, //
        M1911 = 30, //
        Klobbe = 31, //
        VoidMarshal = 32, //
        TearJerker = 33, //
        SmileysRevolver = 35, //
        Megahand = 36, //
        SeriousCannon = 37, //
        Magnum = 38, //
        Rpg = 39, //
        FreezeRay = 40, //
        Heroine = 41, //
        TrankGun = 42, //
        MachinePistol = 43, //
        SkullSpitter = 45, //
        Jolter = 47, //
        SniperRifle = 49, //
        Saa = 50, //
        RegularShotgun = 51, //
        CrescentCrossbow = 52, //
        AuGun = 53, //
        LaserRifle = 54, //
        VoidShotgun = 55, //
        _38Special = 56, //
        AlienSidearm = 57, //
        VoidCoreAssaultRifle = 58, //
        HegemonyRifle = 59, //
        DemonHead = 60, //
        BundleOfWands = 61, //
        Colt1851 = 62, //
        Medkit = 63, // (HealPlayerItem)
        PotionOfLeadSkin = 64, // (ReflectShieldPlayerItem)
        KnifeShield = 65, // (KnifeShieldItem)
        ProximityMine = 66, // (SpawnObjectPlayerItem)
        Key = 67, // (KeyBulletPickup)
        Casing = 68, // (CurrencyPickup)
        BulletTime = 69, // (TimeSlowPlayerItem)
        Unknown2 = 70, // (CurrencyPickup)
        Decoy = 71, // (SpawnObjectPlayerItem)
        BubbleShield = 72, // (ReflectShieldPlayerItem)
        HalfHeart = 73, // (HealthPickup)
        _50Casing = 74, // (CurrencyPickup)
        EyeJewel = 76, // (SimplePuzzleItem)
        SupplyDrop = 77, // (SupplyDropItem)
        Ammo = 78, // (AmmoPickup)
        Makarov = 79, //
        BudgetRevolver = 80, //
        Deck4rd = 81, //
        ElephantGun = 82, //
        UnfinishedGun = 83, //
        VulcanCannon = 84, //
        Heart = 85, // (HealthPickup)
        MarineSidearm = 86, //
        GammaRay = 87, //
        RobotsRightHand = 88, //
        RogueSpecial = 89, //
        EyeOfTheBeholster = 90, //
        H4mmer = 91, //
        Stinger = 92, //
        OldGoldie = 93, //
        Mac10 = 94, //
        Akey47 = 95, //
        M16 = 96, //
        Polaris = 97, //
        Patriot = 98, //
        RustySidearm = 99, //
        UnicornHorn = 100, //
        Scope = 102, // (BasicStatPickup)
        Ration = 104, // (RationItem)
        FortunesFavor = 105, // (FortuneFavorItem)
        Jetpack = 106, // (JetpackItem)
        RaidenCoil = 107, //
        Bomb = 108, // (SpawnObjectPlayerItem)
        IceBomb = 109, // (SpawnObjectPlayerItem)
        MagicSweet = 110, // (BasicStatPickup)
        HeavyBullets = 111, // (BasicStatPickup)
        CartographersRing = 112, // (CartographersRingItem)
        RocketPoweredBullets = 113, // (BasicStatPickup)
        BionicLeg = 114, // (BasicStatPickup)
        Ballot = 115, // (BasicStatPickup)
        AmmoSynthesizer = 116, // (OnKillEnemyItem)
        Eyepatch = 118, // (BasicStatPickup)
        Metronome = 119, // (MetronomeItem)
        Armor = 120, // (HealthPickup)
        Disintegrator = 121, //
        Blunderbuss = 122, //
        PulseCannon = 123, //
        Cactus = 124, //
        FlameHand = 125, //
        Shotbow = 126, //
        Junk = 127, // (BasicStatPickup)
        RubeAdyneMk2 = 128, //
        Com4nd0 = 129, //
        Glacier = 130, //
        UtilityBelt = 131, // (BasicStatPickup)
        RingOfMiserlyProtection = 132, // (MiserlyProtectionItem)
        Backpack = 133, // (BasicStatPickup)
        AmmoBelt = 134, // (BasicStatPickup)
        CogOfBattle = 135, // (CogOfBattleItem)
        C4 = 136, // (RemoteMineItem)
        Map = 137, // (GungeonMapItem)
        Honeycomb = 138, // (SpawnProjectileOnDamagedItem)
        MasterOfUnlocking = 140, // (SpawnItemOnRoomClearItem)
        RubeAdynePrototype = 142, //
        ShotgunFullOfHate = 143, //
        WitchPistol = 145, //
        Dragunfire = 146, //
        PlaceableKey = 147, // (KeyBulletPickup)
        Lies = 148, // (BasicStatPickup)
        FaceMelter = 149, //
        TShirtCannon = 150, //
        TheMembrane = 151, //
        TheKiln = 152, //
        ShockRifle = 153, //
        Trashcannon = 154, //
        Singularity = 155, // (SpawnObjectPlayerItem)
        LaserLotus = 156, //
        BigIron = 157, //
        AmuletOfThePitLord = 158, // (RingOfPitFriendship)
        GundromedaStrain = 159, // (GundromedaStrain)
        GunknightHelmet = 160, // (BulletArmorItem)
        GunknightGreaves = 161, // (BulletArmorItem)
        GunknightGauntlet = 162, // (BulletArmorItem)
        GunknightArmor = 163, // (BulletArmorItem)
        HeartSynthesizer = 164, // (SpawnItemOnRoomClearItem)
        OiledCylinder = 165, // (BasicStatPickup)
        ShelletonKey = 166, // (SkeletonKeyItem)
        BloodyEye = 167, // (EnemyBulletSpeedItem)
        DoubleVision = 168, // (ActiveGunVolleyModificationItem)
        BlackHoleGun = 169, //
        IceCube = 170, // (ActiveItemCooldownItem)
        GhostBullets = 172, // (BasicStatPickup)
        PileOfSouls = 173, // (PileOfDarkSoulsPickup)
        PotionOfGunFriendship = 174, // (ActiveBasicStatItem)
        Tangler = 175, //
        GungeonAnt = 176, //
        AlienEngine = 177, //
        Crestfaller = 178, //
        ProtonBackpack = 179, //
        Grasschopper = 180, //
        WinchesterRifle = 181, //
        GreyMauser = 182, //
        SerManuelsRevolver = 183, //
        TheJudge = 184, //
        MachineFist = 186, //
        DisarmingPersonality = 187, // (BasicStatPickup)
        RollingEye = 190, // (PassiveReflectItem)
        RingOfFireResistance = 191, // (DamageTypeModifierItem)
        BugBoots = 193, // (PassiveGooperItem)
        FossilizedGun = 196, //
        PeaShooter = 197, //
        GunslingersAshes = 198, //
        LuxinCannon = 199, //
        CharmedBow = 200, //
        PortableTurret = 201, // (SpawnObjectPlayerItem)
        SawedOff = 202, //
        Cigarettes = 203, // (SpawnObjectPlayerItem)
        IrradiatedLead = 204, // (BulletStatusEffectItem)
        PoisonVial = 205, // (SpawnObjectPlayerItem)
        CharmHorn = 206, // (RadialCharmItem)
        PlaguePistol = 207, //
        Plunger = 208, //
        SenseOfDirection = 209, // (SenseOfDirectionItem)
        Gunbow = 210, //
        BallisticBoots = 212, // (BasicStatPickup)
        LichyTriggerFinger = 213, // (BasicStatPickup)
        CoinCrown = 214, // (SpawnItemOnRoomClearItem)
        Box = 216, // (CardboardBoxItem)
        OldKnightsShield = 219, // (BasicStatPickup)
        TutorialAk47 = 221, //
        OldKnightsHelm = 222, // (BasicStatPickup)
        Cold45 = 223, //
        Blank = 224, // (SilencerItem)
        IceBreaker = 225, //
        Wristbow = 227, //
        Particulator = 228, //
        HegemonyCarbine = 229, //
        Helix = 230, //
        GildedHydra = 231, //
        SpaceFriend = 232, // (PlayerOrbitalItem)
        IbombCompanionApp = 234, // (BombCompanionAppItem)
        AgedBell = 237, // (RadialSlowItem)
        DuctTape = 239, // (DuctTapeItem)
        Crutch = 240, // (HomingBulletsPassiveItem)
        Scattershot = 241, // (GunVolleyModificationItem)
        NapalmStrike = 242, // (DirectionalAttackActiveItem)
        InfuriatingNote1 = 243, // (NotePassiveItem)
        InfuriatingNote2 = 244, // (NotePassiveItem)
        InfuriatingNote3 = 245, // (NotePassiveItem)
        InfuriatingNote4 = 246, // (NotePassiveItem)
        InfuriatingNote5 = 247, // (NotePassiveItem)
        InfuriatingNote6 = 248, // (NotePassiveItem)
        Owl = 249, // (PlayerOrbitalItem)
        GrapplingHook = 250, // (GrapplingHookItem)
        PrizePistol = 251, //
        AirStrike = 252, // (DirectionalAttackActiveItem)
        GungeonPepper = 253, // (AuraItem)
        RingOfChestFriendship = 254, // (AmazingChestAheadItem)
        AncientHerosBandana = 255, // (BasicStatPickup)
        HeavyBoots = 256, // (HeavyBootsItem)
        Broccoli = 258, // (EyeOfTheTigerItem)
        Antibody = 259, // (HealingReceivedModificationItem)
        PinkGuonStone = 260, // (IounStoneOrbitalItem)
        WhiteGuonStone = 262, // (PlayerOrbitalItem)
        OrangeGuonStone = 263, // (PlayerOrbitalItem)
        ClearGuonStone = 264, // (IounStoneOrbitalItem)
        OldKnightsFlask = 267, // (EstusFlaskItem)
        RedGuonStone = 269, // (IounStoneOrbitalItem)
        BlueGuonStone = 270, // (IounStoneOrbitalItem)
        RiddleOfLead = 271, // (EyeOfTheTigerItem)
        IronCoin = 272, // (IronCoinItem)
        LaserSight = 273, // (LaserSightItem)
        DarkMarker = 274, //
        FlareGun = 275, //
        Spice = 276, // (SpiceItem)
        FatBullets = 277, // (BasicStatPickup)
        FrostBullets = 278, // (BulletStatusEffectItem)
        SuperHotWatch = 279, // (SuperhotItem)
        DrumClip = 280, // (BasicStatPickup)
        GungeonBlueprint = 281, // (CartographersRingItem)
        HomingBullets = 284, // (HomingBulletsPassiveItem)
        BloodBrooch = 285, // (RegenerationPassiveItem)
        _1Bullets = 286, // (BasicStatPickup)
        BackupGun = 287, // (GunVolleyModificationItem)
        BouncyBullets = 288, // (BasicStatPickup)
        SevenLeafClover = 289, // (SevenLeafCloverItem)
        Sunglasses = 290, // (SunglassesItem)
        Meatbun = 291, // (HealPlayerItem)
        MolotovLauncher = 292, //
        MimicToothNecklace = 293, // (MimicToothNecklaceItem)
        RingOfMimicFriendship = 294, // (MimicRingItem)
        HotLead = 295, // (BulletStatusEffectItem)
        MetashopBreachItemOld = 296, // (ItemBlueprintItem) was YariLauncherDupe1
        HegemonyCredit = 297, // (CurrencyPickup)
        ShockRounds = 298, // (ComplexProjectileModifier)
        SuperSpaceTurtlesGun = 299, //
        Dog = 300, // (CompanionItem)
        SuperSpaceTurtle = 301, // (CompanionItem)
        BulletThatCanKillThePast = 303, // (BulletThatCanKillThePast)
        ExplosiveRounds = 304, // (ComplexProjectileModifier)
        OldCrest = 305, // (CathedralCrestItem)
        EscapeRope = 306, // (EscapeRopeItem)
        WaxWings = 307, // (WingsItem)
        ClusterMine = 308, // (SpawnObjectPlayerItem)
        CloranthyRing = 309, // (BasicStatPickup)
        FairyWings = 310, // (WingsItem)
        Clone = 311, // (ExtraLifeItem)
        BlastHelmet = 312, // (HelmetItem)
        MonsterBlood = 313, // (PassiveGooperItem)
        Nanomachines = 314, // (NanomachinesItem)
        Gunboots = 315, // (DownwellBootsItem)
        GnawedKey = 316, // (SpecialKeyItem)
        R2g2 = 318, // (CompanionItem)
        Ticket = 320, // (ActiveSummonItem)
        GoldAmmolet = 321, // (BlankModificationItem)
        LodestoneAmmolet = 322, // (BlankModificationItem)
        AngryBullets = 323, // (ModifyProjectileOnEnemyImpact)
        ChaosAmmolet = 325, // (BlankModificationItem)
        Number2 = 326, // (CoopPassiveItem)
        Corsair = 327, //
        ChargeShot = 328, //
        ZillaShotgun = 329, //
        TheEmperor = 330, //
        ScienceCannon = 331, //
        LilBomber = 332, //
        Mutation = 333, //
        WindUpGun = 334, //
        Silencer = 335, //
        Pitchfork = 336, //
        CompositeGun = 337, //
        Gunther = 338, //
        Mahoguny = 339, //
        LowerCaseR = 340, //
        Buzzkill = 341, //
        UraniumAmmolet = 342, // (BlankModificationItem)
        CopperAmmolet = 343, // (BlankModificationItem)
        FrostAmmolet = 344, // (BlankModificationItem)
        Fightsabre = 345, //
        Huntsman = 346, //
        Shotgrub = 347, //
        PrimePrimer = 348, // (AncientPrimerItem)
        PlanarLead = 349, // (AstralSlugItem)
        ObsidianShellCasing = 350, // (ObsidianShellItem)
        ArcaneGunpowder = 351, // (ArcaneGunpowderItem)
        ShadowBullets = 352, // (ComplexProjectileModifier)
        EnragingPhoto = 353, // (RagePassiveItem)
        MilitaryTraining = 354, // (BasicStatPickup)
        ChromesteelAssaultRifle = 355, //
        TrustyLockpicks = 356, // (LockpicksItem)
        CatClaw = 357, //
        Railgun = 358, //
        CompressedAirTank = 359, //
        Snakemaker = 360, //
        BulletBore = 362, //
        TrickGun = 363, //
        HeartOfIce = 364, // (SpawnProjectileOnDamagedItem)
        MassShotgun = 365, //
        Molotov = 366, // (SpawnObjectPlayerItem)
        HuntersJournal = 367, // (BasicStatPickup)
        ElTigre = 368, //
        BaitLauncher = 369, //
        PrototypeRailgun = 370, //
        RcRocket = 372, //
        AlphaBullets = 373, // (ClipBulletModifierItem)
        OmegaBullets = 374, // (ClipBulletModifierItem)
        EasyReloadBullets = 375, // (MoveAmmoToClipItem)
        BrickBreaker = 376, //
        Excaliber = 377, //
        Derringer = 378, //
        ShotgunFullOfLove = 379, //
        BetrayersShield = 380, //
        TripleCrossbow = 381, //
        Sling = 382, //
        FlashRay = 383, //
        Phoenix = 384, //
        Hexagun = 385, //
        FrostGiant = 387, //
        CobaltHammer = 390, //
        CellKey = 392, // (NPCCellKeyItem)
        Anvillain = 393, //
        MineCutter = 394, //
        StaffOfFirepower = 395, //
        TableTechSight = 396, // (TableFlipItem)
        TableTechMoney = 397, // (TableFlipItem)
        TableTechRocket = 398, // (TableFlipItem)
        TableTechRage = 399, // (TableFlipItem)
        TableTechBlanks = 400, // (TableFlipItem)
        Gungine = 401, //
        Snowballer = 402, //
        MeltedRock = 403, // (CorpseExplodeActiveItem)
        Siren = 404, //
        Rattler = 406, //
        SixthChamber = 407, // (ChamberOfEvilItem)
        BustedTelevision = 409, // (RobotUnlockTelevisionItem)
        BatteryBullets = 410, // (BulletStatusEffectItem)
        CoolantLeak = 411, // (DirectionalAttackActiveItem)
        FriendshipCookie = 412, // (HealPlayerItem)
        HerosSword = 413, // (HeroSwordItem)
        LiveAmmo = 414, // (LiveAmmoItem)
        ReplacementArm = 415, // (RobotArmItem)
        Balloon = 416, // (RobotArmBalloonsItem)
        Blasphemy = 417, //
        TrorcBreachItem = 418, // (ItemBlueprintItem) was BugBootsDupe1
        HeartHolster = 421, // (BasicStatPickup)
        HeartLunchbox = 422, // (BasicStatPickup)
        HeartLocket = 423, // (BasicStatPickup)
        HeartBottle = 424, // (BasicStatPickup)
        HeartPurse = 425, // (BasicStatPickup)
        ShotgaCola = 426, // (BasicStatPickup)
        ShotgunCoffee = 427, // (BasicStatPickup)
        GooptonBreachItem = 429, // (ItemBlueprintItem) was BugBootsDupe2
        LiquidValkyrie = 431, // (EnemyBulletSpeedItem)
        JarOfBees = 432, // (SpawnObjectPlayerItem)
        StuffedStar = 433, // (TemporaryInvulnerabilityPlayerItem)
        BulletIdol = 434, // (OnDamagedPassiveItem)
        Mustache = 435, // (OnPurchasePassiveItem)
        BloodiedScarf = 436, // (BlinkPassiveItem)
        MuscleRelaxant = 437, // (GunClassPassiveItem)
        ExplosiveDecoy = 438, // (SpawnObjectPlayerItem)
        BracketKey = 439, // (DamageEnemiesInRadiusItem)
        RubyBracelet = 440, // (ThrownGunPassiveItem)
        EmeraldBracelet = 441, // (ThrownGunPassiveItem)
        Badge = 442, // (CompanionItem)
        BigBoy = 443, // (TargetedAttackPlayerItem)
        Trident = 444, //
        TheScrambler = 445, //
        ShieldOfTheMaiden = 447, // (ActiveShieldItem)
        Boomerang = 448, // (SpawnObjectPlayerItem)
        TeleporterPrototype = 449, // (TeleporterPrototypeItem)
        ArmorSynthesizer = 450, // (SpawnItemOnRoomClearItem)
        Pig = 451, // (CompanionItem)
        Sponge = 452, // (PassiveGooperItem)
        GasMask = 453, // (DamageTypeModifierItem)
        HazmatSuit = 454, // (DamageTypeModifierItem)
        RingOfTriggers = 456, // (OnPlayerItemUsedItem)
        ArmorOfThorns = 457, // (SpikedArmorItem)
        RingOfEtherealForm = 458, // (GaseousFormPlayerItem)
        ChaffGrenade = 460, // (SpawnObjectPlayerItem)
        BlankCompanionsRing = 461, // (CompanionItem)
        SmokeBomb = 462, // (ConsumableStealthItem)
        RingOfTheResourcefulRat = 463, // (RingOfResourcefulRatItem)
        Shellegun = 464, //
        TableTechStun = 465, // (TableFlipItem)
        GreenGuonStone = 466, // (IounStoneOrbitalItem)
        MasterRound5 = 467, // (BasicStatPickup)
        MasterRound3 = 468, // (BasicStatPickup)
        MasterRound1 = 469, // (BasicStatPickup)
        MasterRound4 = 470, // (BasicStatPickup)
        MasterRound2 = 471, // (BasicStatPickup)
        GummyGun = 472, //
        HiddenCompartment = 473, // (BasicStatPickup)
        AbyssalTentacle = 474, //
        QuadLaser = 475, //
        MicrotransactionGun = 476, //
        Origuni = 477, //
        Banana = 478, //
        SuperMeatGun = 479, //
        MakeshiftCannon = 480, //
        Camera = 481, //
        Gunzheng = 482, //
        Tetrominator = 483, //
        Devolver = 484, //
        Orange = 485, // (HealPlayerItem)
        TreadnaughtCannon = 486, //
        BookOfChestAnatomy = 487, // (ChestBrokenImprovementItem)
        RingOfChestVampirism = 488, // (ChestBrokenItem)
        GunSoul = 489, // (ExtraLifeItem)
        BrickOfCash = 490, // (SnitchBrickItem)
        Wingman = 491, // (PlayerOrbitalItem)
        Wolf = 492, // (CompanionItem)
        BriefcaseOfCash = 493, // (BriefcaseFullOfCashItem)
        GalacticMedalOfValor = 494, // (BasicStatPickup)
        Unity = 495, // (OurPowersCombinedItem)
        MetashopBreachItemGun = 497, // (ItemBlueprintItem) was YariLauncherDupe2
        ElderBlank = 499, // (ReusableBlankitem)
        HipHolster = 500, // (FireOnReloadItem)
        MetashopBreachItemItem = 501, // (ItemBlueprintItem) was YariLauncherDupe3
        HmAbsolutionRockets = 502, // (DoNothingActiveItem)
        Bullet = 503, //
        HyperLightBlaster = 504, //
        MagnumWickedSister = 505, // was HuntsmanDupe1
        ReallySpecialLute = 506, //
        Starpew = 507, //
        DuelingLaser = 508, //
        Jk47 = 510, //
        _3rdPartyController = 511, //
        Shell = 512, //
        Poxcannon = 513, //
        DirectionalPad = 514, //
        MourningStar = 515, //
        TripleGun = 516, //
        TripleGunForm2 = 517, // was TheJudgeDupe1
        TripleGunForm3 = 518, // was TheJudgeDupe2
        CombinedRifle = 519, //
        BalloonGun = 520, //
        ChanceBullets = 521, // (ProjectileRandomizerItem)
        StoutBullets = 523, // (StoutBulletsItem)
        Bloody9mm = 524, // (RandomProjectileReplacementItem)
        LamentConfigurum = 525, // (PuzzleBoxItem)
        SpringheelBoots = 526, // (PegasusBootsItem)
        CharmingRounds = 527, // (BulletStatusEffectItem)
        ZombieBullets = 528, // (ReturnAmmoOnMissedShotItem)
        BattleStandard = 529, // (BattleStandardItem)
        RemoteBullets = 530, // (GuidedBulletsPassiveItem)
        FlakBullets = 531, // (ComplexProjectileModifier)
        GildedBullets = 532, // (ScalingStatBoostItem)
        MagicBullets = 533, // (BulletStatusEffectItem)
        RealCoolBow = 535, // was BowDupe1 (unfinished item???)
        Relodestone = 536, // (RelodestoneItem)
        VorpalGun = 537, //
        SilverBullets = 538, // (SilverBulletsPassiveItem)
        BoxingGlove = 539, //
        GlassCannon = 540, //
        Casey = 541, //
        StrafeGun = 542, //
        ThePredator = 543, //
        Ac15Unarmored = 544, // was PatriotDupe1
        Ac15 = 545, //
        Windgunner = 546, //
        KnightsGun = 550, //
        CrownOfGuns = 551, //
        Bottle = 558, // (EmptyBottleItem)
        TheFatLine = 562, //
        TheExotic = 563, //
        FullMetalJacket = 564, // (AutoblankVestItem)
        GlassGuonStone = 565, // (IounStoneOrbitalItem)
        RadGun = 566, //
        RollBomb = 567, // (FireVolleyOnRollItem)
        HelixBullets = 568, // (GunVolleyModificationItem)
        ChaosBullets = 569, // (ChaosBulletsItem)
        YellowChamber = 570, // (YellowChamberItem)
        CursedBullets = 571, // (ScalingStatBoostItem)
        ChickenFlute = 572, // (CompanionItem)
        ChestTeleporter = 573, // (ChestTeleporterItem)
        WoodenBlasphemy = 574, //
        DougBreachItem = 575, // (ItemBlueprintItem) was BugBootsDupe3
        RobotsLeftHand = 576, //
        TurboGun = 577, //
        Sprun = 578, // (SprenOrbitalItem)
        BlankBullets = 579, // (ComplexProjectileModifier)
        Junkan = 580, // (CompanionItem)
        VoidCoreCannon = 593, //
        MoonlightTiara = 594, //
        LifeOrb = 595, //
        Teapot = 596, //
        MrAccretionJr = 597, //
        StoneDome = 598, //
        BubbleBlaster = 599, //
        PartialAmmo = 600, // (AmmoPickup)
        BigShotgun = 601, //
        Gunner = 602, //
        LameyGun = 603, //
        Slinger = 604, //
        LootBag = 605, // (BankBagItem)
        ClownMask = 607, // (BankMaskItem)
        MutationNeoTechYo = 608, //
        RubeAdyneRubensteinsMonster = 609, //
        WoodBeam = 610, //
        Ak47IslandForme = 611, //
        HeroineWaveBeam = 612, //
        HeroineIceBeam = 613, //
        HeroinePlasmaBeam = 614, //
        HeroineHyberBeam = 615, //
        CaseyCarefulIteration = 616, //
        MegahandQuickBoomerang = 617, //
        MegahandTimeStopper = 618, //
        MegahandMetalBlade = 619, //
        MegahandLeafShield = 620, //
        MegahandAtomicFire = 621, //
        MegahandBubbleLead = 622, //
        MegahandAirShooter = 623, //
        MegahandCrashBomber = 624, //
        Drill = 625, // (PaydayDrillItem)
        Elimentaler = 626, //
        PlatinumBullets = 627, // (PlatinumBulletsItem)
        Bumbullets = 630, // (GunVolleyModificationItem)
        HoleyGrail = 631, // (BlankPersonalityItem)
        Turkey = 632, // (CompanionItem)
        TableTechShotgun = 633, // (TableFlipItem)
        CrisisStone = 634, // (CrisisStoneItem)
        Snowballets = 636, // (SnowballBulletsItem)
        WeirdEgg = 637, // (GungeonEggItem)
        DevolverRounds = 638, // (ComplexProjectileModifier)
        VorpalBullets = 640, // (ComplexProjectileModifier)
        GoldJunk = 641, // (BasicStatPickup)
        Daruma = 643, // (KiPulseItem)
        PortableTableDevice = 644, // (FoldingTableItem)
        TurtleProblem = 645, // (MulticompanionItem)
        ChamberGun = 647, //
        TanglerFullCircle = 648, // was LowerCaseRDupe1
        UppercaseR = 649, //
        PaydayWinchester = 650, //
        RogueSpecialAlt = 651, // was RogueSpecialDupe1
        BudgetRevolverAlt = 652, // was BudgetRevolverDupe1
        GunPiece = 654, // (FragileGunItemPiece)
        HungryBullets = 655, // (ComplexProjectileModifier)
        KrullerGlaive = 656, //
        ChamberGunOubliette = 657, // was FlashRayDupe1
        ChamberGunForge = 658, // was ProtonBackpackDupe1
        ChamberGunHollow = 659, // was TheExoticDupe1
        ChamberGunProper = 660, // was RegularShotgunDupe1
        OrbitalBullets = 661, // (GunVolleyModificationItem)
        PartiallyEatenCheese = 662, // (CheeseWheelItem)
        ResourcefulSack = 663, // (RatPackItem)
        BabyGoodMimic = 664, // (CompanionItem)
        MachoBrace = 665, // (MachoBraceItem)
        TableTechHeat = 666, // (TableFlipItem)
        RatBoots = 667, // (RatBootsItem)
        EnemyElimentaler = 668, //
        HighDragunfire = 670, //
        GammaRayBetaRay = 671, //
        ElephantGunTheElephantInTheRoom = 672, //
        MachinePistolPistolMachine = 673, //
        PeaShooterPeaCannon = 674, //
        DuelingPistolDualingPistol = 675, //
        LaserRifleLaserLightShow = 676, //
        DragunfireKalibreath = 677, //
        BlunderbussBlunderbrace = 678, //
        SnowballerSnowballShotgun = 679, //
        ExcaliberArmoredCorps = 680, //
        _38SpecialDetectiveMode = 681, // was _38SpecialUnknown
        PlaguePistolPandemicPistol = 682, //
        ThunderclapAlistairsLadder = 683, //
        M1M1MultiTool = 684, //
        ThompsonFutureGangster = 685, //
        CorsairBlackFlag = 686, //
        CrestfallerFiveOclockSomewhere = 687, //
        BananaFruitsAndVegetables = 688, //
        AbyssalTentacleKalibersGrip = 689, //
        KlobbeKlobberingTime = 690, //
        MolotovLauncherSpecialReserve = 691, //
        NailGunNailedIt = 692, //
        GunbowShowAcrossTheBow = 693, //
        BigIronIronSlug = 694, //
        HyperLightBlasterHardLight = 695, //
        AlienSidearmChiefMaster = 696, //
        ShockRifleBatteryPowered = 697, //
        FlameHandMaximizeSpell = 698, //
        HegemonyRifleHegemonySpecialForces = 699, //
        CactusCactusFlower = 700, //
        LuxinCannonNoxinCannon = 701, //
        FaceMelterAlternativeRock = 702, //
        BeeHiveApiary = 703, //
        TrashcannonRecyclingBin = 704, //
        FlashRaySaviorOfTheUniverse = 705, //
        FlareGunFiringWithFlair = 706, //
        VulcanCannonNotQuiteAsMini = 707, //
        HelixDoubleDoubleHelix = 708, //
        BarrelLikeShootingFish = 709, //
        FreezeRayIceCap = 710, //
        LightGunPeripheralVision = 711, //
        RaidenCoilRaiden = 712, //
        MoonscraperDoubleMoon7 = 713, //
        LaserLotusLotusBloom = 714, //
        H4mmerHammerAndNail = 715, //
        AwpArcticWarfare = 716, //
        BulletBoreCerebralBros = 717, //
        PolarisSquareBrace = 718, //
        LilBomberKingBomber = 719, //
        ProtonBackpackElectronPack = 720, //
        JolterHeavyJolt = 721, //
        PitchforkPitchPerfect = 722, //
        Com4nd0CommammoBelt = 723, //
        HegemonyCarbineRubyCarbine = 724, //
        TearJerkerUnknown = 725, //
        Akey47AkeyBreaky = 726, //
        RatKey = 727, // (KeyBulletPickup)
        GunderfuryLv50 = 728, // was Unknown7
        GunderfuryLv60 = 729, // was Unknown8
        GunderfuryLv40 = 730, // was Unknown9
        GunderfuryLv30 = 731, // was Unknown10
        GunderfuryLv10 = 732, //
        GunderfuryLv20 = 733, // was Unknown11
        MimicGun = 734, //
        Serpent = 735, // (PlayerOrbitalItem)
        PhoenixPhoenixUp = 736, //
        BetrayersShieldBetrayersLies = 737, //
        LowerCaseRUnknown = 738, //
        GungeonAntGreatQueenAnt = 739, //
        BuzzkillNotSoSawedOff = 740, //
        TearJerkerWrathOfTheBlam = 741, //
        AlienEngineContrail = 742, //
        RadGunKungFuHippieRappinSurfer = 743, //
        OriguniParchmental = 744, //
        IceBreakerGunderlord = 745, //
        TurtineGun = 747, // was HighDragunfireUnknown
        SunlightJavelin = 748, //
        ShotbowSecondAccident = 749, //
        DungeonEagleDontHootTheMessenger = 750, //
        BigGun = 751, // was MagnumUnknownSynergy
        WestBroNomesRevolver = 752, // was SmileysRevolverUnknownSynergy1
        WestBroTucosRevolver = 753, // was SmileysRevolverUnknownSynergy2
        WestBroAngelsRevolver = 754, // was SmileysRevolverUnknownSynergy3
        Evolver = 755, //
        EvolverSponge = 756, // was ShellUnknownSynergy1
        EvolverFlatworm = 757, // was ShellUnknownSynergy2
        EvolverSnail = 758, // was ShellUnknownSynergy3
        EvolverFrog = 759, // was ShellUnknownSynergy4
        EvolverDragon = 760, // was ShellUnknownSynergy5
        HighKaliber = 761, //
        FinishedGun = 762, //
        ChamberGunHell = 763, // was RegularShotgunUnknownSynergy1
        ChamberGunAbbey = 806, // was UnfinishedGunUnknownSynergy2
        ChamberGunMines = 807, // was UnfinishedGunUnknownSynergy3
        ChamberGunRatLair = 808, // was TheExoticUnknownSynergy1
        MarineSidearmAlt = 809, //
        RustySidearmAlt = 810, //
        DartGunAlt = 811, //
        RobotsRightHandAlt = 812, //
        BlasphemyAlt = 813, //
        MagazineRack = 814, // (MagazineRackItem)
        LichsEyeBullets = 815, // (SynergyCompletionItem)
        TrankGunINeedScissors = 816, // was TrankGunDupe1
        CatBulletKingThrone = 817, // (WingsItem)
        BabyGoodShelleton = 818, // (CompanionItem)
        GlassCannonSteelSkin = 819, //
        ShadowClone = 820, // (SpawnObjectPlayerItem)
        Scouter = 821, // (RatchetScouterItem)
        KatanaBullets = 822, // (ComplexProjectileModifier)
        ChamberGunRNG = 823, // was WoodBeamDupe1
    }

    public static class ItemHelper
    {
        public static PickupObject Get(Items i)
        {
            return PickupObjectDatabase.GetById((int)i);
        }
    }

    public class ExtendedColours // stolen from NN
    {
        //New Colours
        public static Color carrionRed = new Color(176 / 255f, 4f / 255f, 4f / 255f);
        public static Color pink = new Color(242f / 255f, 116f / 255f, 225f / 255f);
        public static Color paleYellow = new Color(242f / 255f, 238f / 255f, 148f / 255f);
        public static Color lime = new Color(111f / 255f, 252f / 255f, 3f / 255f);
        public static Color brown = new Color(122f / 255f, 71f / 255f, 16f / 255f);
        public static Color orange = new Color(240f / 255f, 160f / 255f, 22f / 255f);
        public static Color vibrantOrange = new Color(255f / 255f, 144f / 255f, 41f / 255f);
        public static Color purple = new Color(171f / 255f, 22f / 255f, 240f / 255f);
        public static Color skyblue = new Color(130f / 255f, 230f / 255f, 2255f / 255f);
        public static Color honeyYellow = new Color(255f / 255f, 180f / 255f, 18f / 255f);
        public static Color maroon = new Color(105f / 255f, 7f / 255f, 9f / 255f);
        public static Color veryDarkRed = new Color(71f / 255f, 4f / 255f, 3f / 255f);
        public static Color plaguePurple = new Color(242f / 255f, 161f / 255f, 255f / 255f);
        public static Color darkBrown = new Color(74f / 255f, 22f / 255f, 5f / 255f);

        // //Colours  taken from Status effects
        // public static Color freezeBlue = StaticStatusEffects.chaosBulletsFreeze.TintColor;
        // public static Color poisonGreen = StaticStatusEffects.irradiatedLeadEffect.TintColor;
        // public static Color charmPink = StaticStatusEffects.charmingRoundsEffect.TintColor;

        // //Colours taken from items
        // public static Color cursedBulletsPurple = Gungeon.Game.Items["cursed_bullets"].GetComponent<ScalingStatBoostItem>().TintColor;
        // public static Color gildedBulletsGold = Gungeon.Game.Items["gilded_bullets"].GetComponent<ScalingStatBoostItem>().TintColor;
        // public static Color silvedBulletsSilver = Gungeon.Game.Items["silver_bullets"].GetComponent<SilverBulletsPassiveItem>().TintColor;
        // public static Color frostBulletsTint = Gungeon.Game.Items["frost_bullets"].GetComponent<BulletStatusEffectItem>().TintColor;
        // public static Color shadowBulletsBlue = new Color(0.35f, 0.25f, 0.65f, 1f);

    }
}
